name: Build PBRP

on:
  watch:
    types: [started]

jobs:
  SakuraKernel:
    runs-on: ubuntu-latest
    steps:
      - name: 环境准备
        run: |
          sudo apt update -y
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev imagemagick libbz2-dev libssl-dev lzma ncftp bash-completion python openjdk-8-jdk qemu-user-static
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          sudo mv repo /bin/repo
          sudo chmod a+x /bin/repo
          git config --global user.email "m18312827722@126.com"
          git config --global user.name "NightstarSakura"
      - name: 拉取源代码及设备树
        run: |
          mkdir PBRP
          cd PBRP
          repo init -u https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-11.0
          repo sync
          git clone https://github.com/NightstarSakura/android_device_xiaomi_alioth-pbrp -b android-11.0 device/xiaomi/alioth
      - name: 构建REC
        run: |
          cd PBRP
          . build/envsetup.sh
          lunch omni_alioth-eng
          mka pbrp
          ls out/target/product/alioth/
      
